import Head from "next/head";
import styles from "../styles/Home.module.css";

import Header from "../components/Header";
import Footer from "../components/Footer";
import About from "../components/About";
import Resume from "../components/Resume";
import Contact from "../components/Contact";
import Portfolio from "../components/Portfolio";
import { resumeData } from "../public/resumeData";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="App">
				<Header data={resumeData} />
				<About data={resumeData} />
				<Portfolio data={resumeData} />
				<Resume data={resumeData} />
				<Contact data={resumeData} />
				<Footer data={resumeData} />
			</div>
		</div>
	);
}
