import Head from "next/head";

import About from "../components/About";
import Resume from "../components/Resume";
import Contact from "../components/Contact";
import Portfolio from "../components/Portfolio";
import { resumeData } from "../public/resumeData";
import Layout from "../components/layout";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout resumeData={resumeData}>
				<About data={resumeData} />
				<Portfolio data={resumeData} />
				<Resume data={resumeData} />
				<Contact data={resumeData} />
			</Layout>
		</div>
	);
}
